#!/usr/bin/env python3
"""
Build gizmo/SGVersionRead_portable.nk — a self-contained version of SGVersionRead
with all Python module code embedded (no external NUKE_PATH dependency).

Usage:
    python scripts/build_nk.py
"""

import os
import re
import base64
import zipfile
import io

ROOT       = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
NK_SRC     = os.path.join(ROOT, "gizmo", "SGVersionRead.nk")
PYTHON_PKG = os.path.join(ROOT, "python", "SGVersionRead")
OUTPUT_NK  = os.path.join(ROOT, "gizmo", "SGVersionRead_portable.nk")


# ── embed Python package as base64 zip ────────────────────────────────────────

def _zip_package():
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for fname in sorted(os.listdir(PYTHON_PKG)):
            if fname.endswith(".py"):
                fpath = os.path.join(PYTHON_PKG, fname)
                with open(fpath, "r", encoding="utf-8") as f:
                    zf.writestr(f"SGVersionRead/{fname}", f.read())
    return base64.b64encode(buf.getvalue()).decode("ascii")


BOOTSTRAP_TEMPLATE = '''\
import base64, zipfile, io, sys, os, tempfile
_SGVR_B64 = "{b64}"
def _sgvr_bootstrap():
    cache = os.path.join(tempfile.gettempdir(), "sgvr_embed")
    flag  = os.path.join(cache, ".ok")
    if not os.path.exists(flag):
        os.makedirs(cache, exist_ok=True)
        with zipfile.ZipFile(io.BytesIO(base64.b64decode(_SGVR_B64))) as _zf:
            _zf.extractall(cache)
        open(flag, "w").close()
    if cache not in sys.path:
        sys.path.insert(0, cache)
_sgvr_bootstrap()
'''


def _escape_for_nk(code):
    """Escape Python source for embedding inside a double-quoted Nuke knob value."""
    return code.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _patch_oncreate(nk_text, bootstrap):
    """Prepend bootstrap to the onCreate callback string."""
    pattern = re.compile(r'(onCreate\s+")(.*?)(")', re.DOTALL)

    def replacer(m):
        original = m.group(2).replace("\\n", "\n")
        patched = bootstrap + "\n" + original
        return m.group(1) + _escape_for_nk(patched) + m.group(3)

    return pattern.sub(replacer, nk_text)


def build():
    with open(NK_SRC, "r", encoding="utf-8") as f:
        src = f.read()

    b64 = _zip_package()
    bootstrap = BOOTSTRAP_TEMPLATE.format(b64=b64)
    src = _patch_oncreate(src, bootstrap)

    with open(OUTPUT_NK, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by scripts/build_nk.py — do not edit manually.\n")
        f.write("# Python module is embedded; no NUKE_PATH setup required.\n\n")
        f.write(src)

    size = os.path.getsize(OUTPUT_NK) / 1024
    print(f"Built {OUTPUT_NK}  ({size:.1f} kB)")


if __name__ == "__main__":
    build()
